services:
  - type: web
    name: task-service
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --chdir cmd main:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: task-service-db
          property: connectionString

databases:
  - name: task-service-db
    databaseName: task_service
    ipAllowList: []  # Allow all IPs
